language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10-dev'
  - 'pypy'
  - 'pypy3'

before_install:
  - sudo apt-get -y install libzbar0

install:
  - pip install -r requirements-testing.txt
  - if [[ ! $TRAVIS_PYTHON_VERSION =~ ^2 && ! $TRAVIS_PYTHON_VERSION =~ ^pypy ]]; then pip install flake8; fi
  - if [[ ! $TRAVIS_PYTHON_VERSION =~ ^2 && ! $TRAVIS_PYTHON_VERSION =~ ^pypy ]]; then pip install mypy; fi

script:
  - if [[ ! $TRAVIS_PYTHON_VERSION =~ ^2 && ! $TRAVIS_PYTHON_VERSION =~ ^pypy ]]; then flake8 segno; fi
  - if [[ ! $TRAVIS_PYTHON_VERSION =~ ^2 && ! $TRAVIS_PYTHON_VERSION =~ ^pypy ]]; then flake8 tests/; fi
  - if [[ ! $TRAVIS_PYTHON_VERSION =~ ^2 && ! $TRAVIS_PYTHON_VERSION =~ ^pypy ]]; then mypy segno; fi
  - pytest
