language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10-dev'
  - 'pypy'
  - 'pypy3'

install:
  - pip install -r requirements-testing.txt

script:
  - flake8 segno
  - flake8 tests/
  - if [[ ! $TRAVIS_PYTHON_VERSION =~ ^2 ]]; then mypy segno; fi
  - pytest
